/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.css': { assetKey: '/index.css', contentType: 'text/css', isText: true, fileInfo: { size: 468, hash: 'a6185fa7d1e88f93a0b49cbe95f9c128064fbd95e8812c975f9501af24a1043d', lastModifiedTime: 1758634982, assetPath: './styles/index.css' }, lastModifiedTime: 1758634982, type: 'wasm-inline' },
};

export { staticAssetManifest };
