/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.html': { assetKey: '/index.html', contentType: 'text/html', isText: true, fileInfo: { size: 985, hash: 'a291170d680d7fda8e4fc8695e4222263464938a1efbbaa2f9e1684de3e602cc', lastModifiedTime: 1758634982, assetPath: './templates/index.html' }, lastModifiedTime: 1758634982, type: 'wasm-inline' },
};

export { staticAssetManifest };
