/*
 * DO NOT EDIT THIS FILE - Generated by @gcoredev/FastEdge-sdk-js
 *
 * It will be overwritten on the next build.
 */

const staticAssetManifest = {
  '/index.html': { assetKey: '/index.html', contentType: 'text/html', isText: true, fileInfo: { size: 958, hash: 'c1eda687a1261792bee2e8284594d3d281a0392b2d0dc134259c1cbb94d58922', lastModifiedTime: 1758702663, assetPath: './templates/index.html' }, lastModifiedTime: 1758702663, type: 'wasm-inline' },
};

export { staticAssetManifest };
